/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../../../common";

export declare namespace IBaseSacrifice {
  export type PriceParamStruct = {
    priceMaxPeriod: PromiseOrValue<BigNumberish>;
    minimumPrice: PromiseOrValue<BigNumberish>;
    maximumPrice: PromiseOrValue<BigNumberish>;
  };

  export type PriceParamStructOutput = [BigNumber, BigNumber, BigNumber] & {
    priceMaxPeriod: BigNumber;
    minimumPrice: BigNumber;
    maximumPrice: BigNumber;
  };
}

export interface IBaseSacrificeInterface extends utils.Interface {
  functions: {
    "getPrice()": FunctionFragment;
    "sacrifice(uint256,address)": FunctionFragment;
    "sacrificeToken()": FunctionFragment;
    "setCustomPrice(uint256)": FunctionFragment;
    "setOriginTime(uint64)": FunctionFragment;
    "setPriceParams((uint64,uint128,uint128))": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "getPrice"
      | "sacrifice"
      | "sacrificeToken"
      | "setCustomPrice"
      | "setOriginTime"
      | "setPriceParams"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "sacrifice",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "sacrificeToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setCustomPrice",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setOriginTime",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPriceParams",
    values: [IBaseSacrifice.PriceParamStruct]
  ): string;

  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sacrifice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "sacrificeToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCustomPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setOriginTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPriceParams",
    data: BytesLike
  ): Result;

  events: {
    "CustomPriceSet(uint256)": EventFragment;
    "OriginTimeSet(uint64)": EventFragment;
    "PartnerZeroSacrificed(address,uint256,uint256)": EventFragment;
    "PriceParamsSet(tuple)": EventFragment;
    "RelicMintCapSet(uint256)": EventFragment;
    "TokenRecipientSet(address)": EventFragment;
    "TokenSacrificed(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "CustomPriceSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OriginTimeSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PartnerZeroSacrificed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PriceParamsSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "RelicMintCapSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenRecipientSet"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "TokenSacrificed"): EventFragment;
}

export interface CustomPriceSetEventObject {
  price: BigNumber;
}
export type CustomPriceSetEvent = TypedEvent<
  [BigNumber],
  CustomPriceSetEventObject
>;

export type CustomPriceSetEventFilter = TypedEventFilter<CustomPriceSetEvent>;

export interface OriginTimeSetEventObject {
  originTime: BigNumber;
}
export type OriginTimeSetEvent = TypedEvent<
  [BigNumber],
  OriginTimeSetEventObject
>;

export type OriginTimeSetEventFilter = TypedEventFilter<OriginTimeSetEvent>;

export interface PartnerZeroSacrificedEventObject {
  to: string;
  relicId: BigNumber;
  enclaveId: BigNumber;
}
export type PartnerZeroSacrificedEvent = TypedEvent<
  [string, BigNumber, BigNumber],
  PartnerZeroSacrificedEventObject
>;

export type PartnerZeroSacrificedEventFilter =
  TypedEventFilter<PartnerZeroSacrificedEvent>;

export interface PriceParamsSetEventObject {
  params: IBaseSacrifice.PriceParamStructOutput;
}
export type PriceParamsSetEvent = TypedEvent<
  [IBaseSacrifice.PriceParamStructOutput],
  PriceParamsSetEventObject
>;

export type PriceParamsSetEventFilter = TypedEventFilter<PriceParamsSetEvent>;

export interface RelicMintCapSetEventObject {
  cap: BigNumber;
}
export type RelicMintCapSetEvent = TypedEvent<
  [BigNumber],
  RelicMintCapSetEventObject
>;

export type RelicMintCapSetEventFilter = TypedEventFilter<RelicMintCapSetEvent>;

export interface TokenRecipientSetEventObject {
  recipient: string;
}
export type TokenRecipientSetEvent = TypedEvent<
  [string],
  TokenRecipientSetEventObject
>;

export type TokenRecipientSetEventFilter =
  TypedEventFilter<TokenRecipientSetEvent>;

export interface TokenSacrificedEventObject {
  fromAccount: string;
  token: string;
  amount: BigNumber;
}
export type TokenSacrificedEvent = TypedEvent<
  [string, string, BigNumber],
  TokenSacrificedEventObject
>;

export type TokenSacrificedEventFilter = TypedEventFilter<TokenSacrificedEvent>;

export interface IBaseSacrifice extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IBaseSacrificeInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getPrice(overrides?: CallOverrides): Promise<[BigNumber]>;

    sacrifice(
      enclaveId: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    sacrificeToken(overrides?: CallOverrides): Promise<[string]>;

    setCustomPrice(
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setOriginTime(
      _originTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPriceParams(
      _priceParams: IBaseSacrifice.PriceParamStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  getPrice(overrides?: CallOverrides): Promise<BigNumber>;

  sacrifice(
    enclaveId: PromiseOrValue<BigNumberish>,
    to: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  sacrificeToken(overrides?: CallOverrides): Promise<string>;

  setCustomPrice(
    _price: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setOriginTime(
    _originTime: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPriceParams(
    _priceParams: IBaseSacrifice.PriceParamStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getPrice(overrides?: CallOverrides): Promise<BigNumber>;

    sacrifice(
      enclaveId: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    sacrificeToken(overrides?: CallOverrides): Promise<string>;

    setCustomPrice(
      _price: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setOriginTime(
      _originTime: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPriceParams(
      _priceParams: IBaseSacrifice.PriceParamStruct,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "CustomPriceSet(uint256)"(price?: null): CustomPriceSetEventFilter;
    CustomPriceSet(price?: null): CustomPriceSetEventFilter;

    "OriginTimeSet(uint64)"(originTime?: null): OriginTimeSetEventFilter;
    OriginTimeSet(originTime?: null): OriginTimeSetEventFilter;

    "PartnerZeroSacrificed(address,uint256,uint256)"(
      to?: PromiseOrValue<string> | null,
      relicId?: null,
      enclaveId?: null
    ): PartnerZeroSacrificedEventFilter;
    PartnerZeroSacrificed(
      to?: PromiseOrValue<string> | null,
      relicId?: null,
      enclaveId?: null
    ): PartnerZeroSacrificedEventFilter;

    "PriceParamsSet(tuple)"(params?: null): PriceParamsSetEventFilter;
    PriceParamsSet(params?: null): PriceParamsSetEventFilter;

    "RelicMintCapSet(uint256)"(cap?: null): RelicMintCapSetEventFilter;
    RelicMintCapSet(cap?: null): RelicMintCapSetEventFilter;

    "TokenRecipientSet(address)"(
      recipient?: null
    ): TokenRecipientSetEventFilter;
    TokenRecipientSet(recipient?: null): TokenRecipientSetEventFilter;

    "TokenSacrificed(address,address,uint256)"(
      fromAccount?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: null
    ): TokenSacrificedEventFilter;
    TokenSacrificed(
      fromAccount?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: null
    ): TokenSacrificedEventFilter;
  };

  estimateGas: {
    getPrice(overrides?: CallOverrides): Promise<BigNumber>;

    sacrifice(
      enclaveId: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    sacrificeToken(overrides?: CallOverrides): Promise<BigNumber>;

    setCustomPrice(
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setOriginTime(
      _originTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPriceParams(
      _priceParams: IBaseSacrifice.PriceParamStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    sacrifice(
      enclaveId: PromiseOrValue<BigNumberish>,
      to: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    sacrificeToken(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setCustomPrice(
      _price: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setOriginTime(
      _originTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPriceParams(
      _priceParams: IBaseSacrifice.PriceParamStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
