/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IBaseSacrifice } from "./IBaseSacrifice";
export type { IPartnerSacrifice } from "./IPartnerSacrifice";
export type { ISacrifice } from "./ISacrifice";
