/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC721ACustom } from "./ERC721ACustom";
export type { ERC721A__IERC721Receiver } from "./ERC721A__IERC721Receiver";
