/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, Signer, utils } from "ethers";
import type { EventFragment } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface CommonEventsAndErrorsInterface extends utils.Interface {
  functions: {};

  events: {
    "TokenRecovered(address,address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "TokenRecovered"): EventFragment;
}

export interface TokenRecoveredEventObject {
  to: string;
  token: string;
  amount: BigNumber;
}
export type TokenRecoveredEvent = TypedEvent<
  [string, string, BigNumber],
  TokenRecoveredEventObject
>;

export type TokenRecoveredEventFilter = TypedEventFilter<TokenRecoveredEvent>;

export interface CommonEventsAndErrors extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CommonEventsAndErrorsInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {};

  callStatic: {};

  filters: {
    "TokenRecovered(address,address,uint256)"(
      to?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: null
    ): TokenRecoveredEventFilter;
    TokenRecovered(
      to?: PromiseOrValue<string> | null,
      token?: PromiseOrValue<string> | null,
      amount?: null
    ): TokenRecoveredEventFilter;
  };

  estimateGas: {};

  populateTransaction: {};
}
