/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc721ACustomSol from "./ERC721ACustom.sol";
export type { erc721ACustomSol };
import type * as access from "./access";
export type { access };
export type { BaseSacrifice } from "./BaseSacrifice";
export type { NexusCommon } from "./NexusCommon";
export type { PartnerZeroSacrifice } from "./PartnerZeroSacrifice";
export type { Relic } from "./Relic";
export type { Shard } from "./Shard";
export type { TempleSacrifice } from "./TempleSacrifice";
