/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IBaseSacrifice__factory } from "./IBaseSacrifice__factory";
export { IPartnerSacrifice__factory } from "./IPartnerSacrifice__factory";
export { ISacrifice__factory } from "./ISacrifice__factory";
